using System.ComponentModel.DataAnnotations;

namespace ASL.LivingGrid.WebAdminPanel.Models;

public class TranslationRequest : BaseEntity
{
    [Required]
    [StringLength(200)]
    public string Key { get; set; } = string.Empty;

    [Required]
    [StringLength(10)]
    public string Culture { get; set; } = string.Empty;

    public string? ProposedValue { get; set; }

    [StringLength(100)]
    public string RequestedBy { get; set; } = string.Empty;

    public TranslationRequestStatus Status { get; set; } = TranslationRequestStatus.PendingReview;

    [StringLength(100)]
    public string? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    [StringLength(100)]
    public string? RejectedBy { get; set; }

    public DateTime? RejectedAt { get; set; }

    [StringLength(500)]
    public string? ReviewerComments { get; set; }

    public bool Escalate { get; set; }
}

public enum TranslationRequestStatus
{
    /// <summary>Translation was generated by machine and awaits proofreading.</summary>
    Machine,
    /// <summary>Translation was provided by a human translator and awaits proofreading.</summary>
    Human,
    /// <summary>Proofreader is currently reviewing the translation.</summary>
    PendingReview,
    /// <summary>Proofreader approved a machine generated translation.</summary>
    MachineApproved,
    /// <summary>Proofreader approved a human provided translation.</summary>
    HumanApproved,
    /// <summary>Proofreader approved the translation (source unknown).</summary>
    Approved,
    /// <summary>Translation was reviewed and rejected.</summary>
    Rejected
}
